name: sticky_grouped_list
description: A ScrollablePositionedList where the list items can be grouped into sections.
version: 2.0.0-nullsafety.1
homepage: https://begnis.dev
repository: https://github.com/Dimibe/sticky_grouped_list

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter